# Crucial: This tells Spring to listen on the port Railway assigns dynamically
server.port=${PORT:8080}

# This tells Spring where to find your MongoDB
spring.data.mongodb.uri=${MONGO_URL}

# (This fixes the 'Database name must not be empty' error)
spring.data.mongodb.database=test